name: Daily Baekjoon Crawling

on:
  schedule:
    - cron: '0 15 * * *' # 매일 한국 시간 00시 (UTC 15시)
  push:
    branches: [ main ] # 코드가 push될 때도 실행

permissions:
  contents: write #저장소에 내용을 쓸 수 있는 권한 부여
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install axios

      - name: Run Crawler
        run: node getUserInfoList.js # js 파일 실행

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f userInfoList.json
          git add -f news.json
          git commit -m "Update userInfoList, news data" || echo "No changes to commit"
          git push
